NMS_INDEX1 = "./data/index.bin"
NMS_INDEX2 = "./data/index.bin.dat"
SQLITE_DATASET = "./data/wine.db"
CSV_DATASET = "./data/data.csv"
# SENTENCE_TRANSFORMER_MODEL_NAME = "distilbert-base-uncased"
SENTENCE_TRANSFORMER_MODEL_NAME = "msmarco-distilbert-base-v4"